# filebeat.config.modules:  
#   path: ${path.config}/modules.d/*.yml
#   reload.enabled: true

filebeat.modules:
  - module: qlog
  
output.elasticsearch:
  hosts: ["elasticsearch:9200"]

#setup.template.index.number_of_shards: 3

setup.ilm.enabled: auto
setup.ilm.rollover_alias: "qlog"
setup.ilm.pattern: "{now/d}-000001" 

setup.template.name: "qlog"
setup.template.fields: "./qlog-fields.yml"
